name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job will test the lambda files
  test_lambda_with_jest:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      
      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Installing yarn 
        run: npm install -g yarn

      - name: Installing project dependencies
        run: cd lambda && yarn
        
      - name: Run all tests
        run: cd lambda && yarn coverage

      - name: Save coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  test_lambda_with_postman:
    runs-on: ubuntu-latest
    env:
      DEV_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
      GIT_ACTION: ${{ secrets.DEV_ENVIRONMENT }}

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      
      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Installing yarn 
        run: npm install -g yarn

      - name: Installing project dependencies
        run: cd lambda && yarn

      - name: Run locally
        run: bash deploy.sh lambda test

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: /lambda/tests/postman/collection.json
          environment: /lambda/tests/postman/environment.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}

  # This job will check the lint
  lint_lambda:
    runs-on: ubuntu-latest
        
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      
      - name: Installing yarn
        run: npm install -g yarn
      
      - name: Installing project dependencies
        run: cd lambda && yarn

      - name: Check the code lint
        run: cd lambda && yarn lint

  # Deploy all changes to dev environment
  # deploy_lambda:
  #   runs-on: ubuntu-latest
  #   needs: [test_lambda, lint_lambda]
    
  #   env:
  #     DEV_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
    
  #   steps:
  #     - name: Cloning the repository
  #       uses: actions/checkout@v2
      
  #     - name: Installing and cofiguring node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '10'
  #     - run: npm install -g yarn

  #     - name: Deploying to dev
  #       run: bash deploy.sh lambda dev
