name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job will test the lambda files
  test_lambda:
    runs-on: ubuntu-latest
    
    # env:
    #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      
      - name: Installing and cofiguring node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install -g yarn

      - name: Run all tests
        run: cd lambda && yarn && yarn coverage
      
      - name: Installing curl
        run: apt install curl
        
      # - name: Save coverage report
      #   run: yarn codecov && bash <(curl -s https://codecov.io/bash)

  # This job will check the lint
  lint_lambda:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing and cofiguring node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install -g yarn

      - name: Check the code lint
        exrun: cd lambda && yarn && yarn lint

  # Deploy all changes to dev environment
  deploy_lambda:
    runs-on: ubuntu-latest
    needs: [test_lambda, lint_lambda]
    
    env:
      DEV_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
    
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2
      
      - name: Installing and cofiguring node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install -g yarn

      - name: Deploying to dev
        run: bash deploy.sh lambda dev
